"""05_model_PromoCode_and_PromoCodeUsage

Revision ID: 1985324c8833
Revises: f252a4b826cf
Create Date: 2026-07-27 13:41:55.927021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1985324c8833'
down_revision: Union[str, Sequence[str], None] = 'f252a4b826cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tokens_amount', sa.Integer(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.CheckConstraint('max_uses IS NULL OR max_uses > 0', name='promocode_max_uses_valid'),
    sa.CheckConstraint('max_uses_per_user IS NULL OR max_uses_per_user > 0', name='promocode_max_uses_per_user_valid'),
    sa.CheckConstraint('tokens_amount IS NULL OR tokens_amount > 0', name='promocode_tokens_amount_valid'),
    sa.CheckConstraint('used_count >= 0', name='promocode_used_count_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_code'), 'promo_code', ['code'], unique=True)
    op.create_table('promo_code_usage',
    sa.Column('promocode_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.ForeignKeyConstraint(['promocode_id'], ['promo_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_usage_promocode_id'), 'promo_code_usage', ['promocode_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usage_user_id'), 'promo_code_usage', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_index(op.f('ix_promo_code_usage_user_id'), table_name='promo_code_usage')
    op.drop_index(op.f('ix_promo_code_usage_promocode_id'), table_name='promo_code_usage')
    op.drop_table('promo_code_usage')
    op.drop_index(op.f('ix_promo_code_code'), table_name='promo_code')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
