"""03_model_style

Revision ID: 20ee88470014
Revises: 9a3f2c7d1b80
Create Date: 2026-07-25 12:57:16.997204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ee88470014'
down_revision: Union[str, Sequence[str], None] = '9a3f2c7d1b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style',
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.String(length=1024), nullable=True),
    sa.Column('prompt', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_style_file_id'), 'style', ['file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_file_id'), table_name='style')
    op.drop_table('style')
    # ### end Alembic commands ###
